In [1]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [2]:
env = gym.make("FrozenLake-v0")

In [3]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))

In [4]:
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.01

In [6]:
rewards_all_episodes = []

In [7]:
# Q-learning algorithm
for episode in range(num_episodes):
    # initialize new episode params
    state = env.reset()
    done = False
    rewards_current_episode = 0
    for step in range(max_steps_per_episode): 
        
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        
        # Take new action
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:]) 
        else:
            action = env.action_space.sample()
        
        new_state, reward, done, info = env.step(action)
        # Update Q-table
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        # Set new state
        state = new_state
        
        # Add new reward        
        rewards_current_episode += reward 
    # Exploration rate decay 
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    # Add current episode reward to total rewards list
    rewards_all_episodes.append(rewards_current_episode)

In [9]:
# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000



********Average reward per thousand episodes********

1000 :  0.05000000000000004
2000 :  0.07800000000000006
3000 :  0.1460000000000001
4000 :  0.3140000000000002
5000 :  0.46500000000000036
6000 :  0.5260000000000004
7000 :  0.5790000000000004
8000 :  0.5900000000000004
9000 :  0.6410000000000005
10000 :  0.6360000000000005


In [10]:
# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)



********Q-table********

[[0.51001002 0.3771912  0.45101079 0.46461161]
 [0.22556775 0.08246647 0.01453373 0.03769256]
 [0.01553907 0.05937868 0.03833924 0.17351397]
 [0.02457559 0.08265362 0.         0.00817492]
 [0.52611261 0.24999495 0.41934255 0.25325109]
 [0.         0.         0.         0.        ]
 [0.23095779 0.0532785  0.06930873 0.02795499]
 [0.         0.         0.         0.        ]
 [0.31026026 0.36332179 0.34440219 0.55401157]
 [0.45294497 0.61357919 0.37593802 0.37547123]
 [0.53568981 0.43769234 0.344518   0.1148443 ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.37443911 0.33455879 0.73269605 0.57592671]
 [0.6765067  0.86759149 0.70880433 0.70262568]
 [0.         0.         0.         0.        ]]
