In [1]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [2]:
env = gym.make("FrozenLake-v0")

In [3]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))

In [4]:
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.01

In [15]:
rewards_all_episodes = []

In [16]:
# Q-learning algorithm
for episode in range(num_episodes):
    # initialize new episode params
    state = env.reset()
    done = False
    rewards_current_episode = 0
    for step in range(max_steps_per_episode): 
        
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        
        # Take new action
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:]) 
        else:
            action = env.action_space.sample()
        
        new_state, reward, done, info = env.step(action)
        # Update Q-table
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        # Set new state
        state = new_state
        
        # Add new reward        
        rewards_current_episode += reward 
    # Exploration rate decay 
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    # Add current episode reward to total rewards list
    rewards_all_episodes.append(rewards_current_episode)

In [17]:
# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000



********Average reward per thousand episodes********

1000 :  0.5040000000000003
2000 :  0.6860000000000005
3000 :  0.6630000000000005
4000 :  0.6690000000000005
5000 :  0.6910000000000005
6000 :  0.6580000000000005
7000 :  0.6760000000000005
8000 :  0.6680000000000005
9000 :  0.6670000000000005
10000 :  0.6950000000000005


In [18]:
# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)



********Q-table********

[[0.54916998 0.52301598 0.521331   0.52250597]
 [0.29444705 0.25573801 0.41912463 0.51736675]
 [0.42220899 0.40370626 0.38550309 0.47873385]
 [0.26923638 0.26681536 0.28930336 0.46156995]
 [0.57254621 0.50165641 0.31987275 0.35237162]
 [0.         0.         0.         0.        ]
 [0.2397147  0.18073587 0.28698898 0.09349688]
 [0.         0.         0.         0.        ]
 [0.3859983  0.44491525 0.39143398 0.60748218]
 [0.32736026 0.65365512 0.35591178 0.30723462]
 [0.58899968 0.27090901 0.41172901 0.3089778 ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.51045259 0.36871247 0.73227943 0.48492961]
 [0.68463075 0.85590566 0.76197281 0.74379211]
 [0.         0.         0.         0.        ]]


In [19]:
# Watch our agent play Frozen Lake by playing the best action 
# from each state according to the Q-table

for episode in range(3):
    # initialize new episode params
    state = env.reset()
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)
    for step in range(max_steps_per_episode):        
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        # Show current state of environment on screen
        # Choose action with highest Q-value for current state       
        action = np.argmax(q_table[state,:])        
        # Take new action
        new_state, reward, done, info = env.step(action)
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                # Agent reached the goal and won episode
                print("****You reached the goal!****")
                time.sleep(3)
            else:
                # Agent stepped in a hole and lost episode            
                print("****You fell through a hole!****")
                time.sleep(3)
                clear_output(wait=True)
        
        # Set new state
        
env.close()

IndentationError: expected an indented block (<ipython-input-19-14b0f2576c41>, line 15)